INSERT INTO CUSTOMER(HN,PID,NAME,BIRTHDAY,SEX,BLOOD,NATION,RACE,ADDRESS,TEL,MOBILE,JOB,EMAIL)
values('100','1730200213549','jasin','1993-07-28','M','B','thai','thai','155/8','034589948','0964747468','ProProgrammer','meta.vin@hotmail.com');


INSERT INTO MEDICALHISTORY(DISEASE) values('Nomal');
INSERT INTO MEDICALHISTORY(DISEASE) values('High Blood Pressure');
INSERT INTO MEDICALHISTORY(DISEASE) values('Anemia');
INSERT INTO MEDICALHISTORY(DISEASE) values('Diabetes');
INSERT INTO MEDICALHISTORY(DISEASE) values('Dissolves blood clots');
INSERT INTO MEDICALHISTORY(DISEASE) values('Heart disease');
INSERT INTO MEDICALHISTORY(DISEASE) values('Hepatitis');
INSERT INTO MEDICALHISTORY(DISEASE) values('Losers drug history');



