INSERT INTO CUSTOMER(HN,PID,NAME,BIRTHDAY,SEX,BLOOD,NATION,RACE,ADDRESS,TEL,MOBILE,JOB,EMAIL)
values('100','1730200213549','jasin','1993-07-28','M','B','thai','thai','155/8','034589948','0964747468','ProProgrammer','meta.vin@hotmail.com');

INSERT INTO DEPARTMENTEMPLOYEE(NAME) values('software development');
INSERT INTO DEPARTMENTEMPLOYEE(NAME) values('software Engineering');
INSERT INTO DEPARTMENTEMPLOYEE(NAME) values('software singular');

INSERT INTO MEDICALHISTORY(DISEASE) values('Nomal');
INSERT INTO MEDICALHISTORY(DISEASE) values('High Blood Pressure');
INSERT INTO MEDICALHISTORY(DISEASE) values('Anemia');
INSERT INTO MEDICALHISTORY(DISEASE) values('Diabetes');
INSERT INTO MEDICALHISTORY(DISEASE) values('Dissolves blood clots');
INSERT INTO MEDICALHISTORY(DISEASE) values('Heart disease');
INSERT INTO MEDICALHISTORY(DISEASE) values('Hepatitis');
INSERT INTO MEDICALHISTORY(DISEASE) values('Losers drug history');

INSERT INTO STAFF(WORD_STATUS,EMAIL,NAMETH,MOBILE,ENABLED) values('makework','Staff@staff.com','STAFF','0964747468',TRUE);

INSERT INTO DOCTOR(WORD_STATUS,CER_NO,EMAIL,NAMETH,MOBILE,ENABLED) values('makework','123CERN','Doctor@Doctor.com','DOCTOR','0964747468',TRUE);

INSERT INTO AUTHORITY(ROLES) values('add');
INSERT INTO AUTHORITY(ROLES) values('update');
INSERT INTO AUTHORITY(ROLES) values('delete');


